[build-system]
requires = ["setuptools>=80"]
build-backend = "setuptools.build_meta"

[project]
name = "serviceaid"
version = "0.0.1"
description = "KERI Service AID serverless framework"
requires-python = ">=3.12"
dependencies = ["keri", "boto3>=1.34.0"]

[project.optional-dependencies]
dev = ["moto>=5.0", "pytest>=9.0.2"]
cdk = ["aws-cdk-lib>=2.140.0", "constructs>=10.0.0"]

[tool.setuptools.packages.find]
where = ["."]
include = ["serviceaid*"]
