# -*- encoding: utf-8 -*-
"""
keri.app.configing module

"""
import json
import os
from abc import ABC, abstractmethod
from dataclasses import dataclass, field

import cbor2 as cbor
import hjson
import msgpack
from hio.base import filing, doing

from .. import help

logger = help.ogler.getLogger()


# Known global keys in the config schema
GLOBAL_KEYS = frozenset({"dt", "iurls", "durls", "wurls"})


@dataclass
class Endage:
    """Per-hab endpoint configuration data container.
    Contains controller endpoint URLs for a specific habitat.
    """
    dt: str = ''
    curls: list = field(default_factory=list)


@dataclass
class Bootage:
    """Global bootstrap configuration data container.
    Contains OOBI URLs for initial database seeding.
    """
    dt: str = ''
    iurls: list = field(default_factory=list)
    durls: list = field(default_factory=list)
    wurls: list = field(default_factory=list)


@dataclass
class Confitage:
    """Complete typed configuration envelope.
    Separates global bootstrap data from per-hab endpoint data.
    """
    boot: Bootage = field(default_factory=Bootage)
    habs: dict = field(default_factory=dict)   # str -> Endage
    extra: dict = field(default_factory=dict)   # extension keys (e.g., keria)


def parseConfig(raw):
    """Parse raw config dict into typed Confitage.

    Supports two formats:
      New format: hab sections under explicit "habs" key (no collision risk)
      Legacy format: hab sections as top-level keys (backward compat)

    A top-level key is treated as a hab section if:
      - it is not in GLOBAL_KEYS
      - it is not "habs"
      - its value is a dict containing "curls"

    Parameters:
        raw (dict): raw config data from Sourcer.get()

    Returns:
        Confitage: typed configuration envelope
    """
    if not raw:
        return Confitage()

    boot = Bootage(
        dt=raw.get("dt", ""),
        iurls=list(raw.get("iurls", [])),
        durls=list(raw.get("durls", [])),
        wurls=list(raw.get("wurls", [])),
    )

    habs = {}
    extra = {}

    # New format: explicit "habs" key
    if "habs" in raw and isinstance(raw["habs"], dict):
        for name, val in raw["habs"].items():
            if isinstance(val, dict):
                habs[name] = Endage(
                    dt=val.get("dt", ""),
                    curls=list(val.get("curls", [])),
                )
        for key, val in raw.items():
            if key not in GLOBAL_KEYS and key != "habs":
                extra[key] = val
    else:
        # Legacy format: hab sections are top-level keys
        for key, val in raw.items():
            if key in GLOBAL_KEYS:
                continue
            if isinstance(val, dict) and "curls" in val:
                habs[key] = Endage(
                    dt=val.get("dt", ""),
                    curls=list(val.get("curls", [])),
                )
            else:
                extra[key] = val

    return Confitage(boot=boot, habs=habs, extra=extra)


class Sourcer(ABC):
    """Abstract base class for configuration data sources.

    'One who sources configuration data.' Provides raw config dict
    from any backend (file, memory, database). Parsing into typed
    Confitage is handled separately by parseConfig().

    Pure interface - no lifecycle methods (open/close). Implementations
    that need lifecycle management (e.g., file handles, DB connections)
    handle it internally in their get()/put() or via their own
    inheritance (e.g., FileConfiger gets lifecycle from filing.Filer).
    """

    @abstractmethod
    def get(self):
        """Return config data as a dict.

        Returns:
            dict: raw configuration data, empty dict if no data stored
        """

    @abstractmethod
    def put(self, data):
        """Store config data.

        Parameters:
            data (dict): configuration data to store

        Returns:
            bool: True on success
        """


def openCF(cls=None, filed=True, **kwa):
    """
    Returns contextmanager generated by openFiler with FileConfiger instance
    as default and filed = True
    """
    if cls == None:  # can't reference class before its defined below
        cls = FileConfiger
    return filing.openFiler(cls=cls, filed=filed, **kwa)


class FileConfiger(Sourcer, filing.Filer):
    """
    Habitat Config File

    Supports four serializations. HJSON, JSON, MGPK (MsgPack), and CBOR
    The serialization is determined by the file extension .fext which may be
    either '.json', '.mgpk', or '.cbor'.  The default is that .json extension
    uses HJSON because HJSON can get (load) a strict json file.
    To use strict json on put (dump) then set .human to false.

    See https://github.com/hjson/hjson-py

    Attributes:  (see Filer for inherited attributes)
        human (bool): True (default) means use human friendly HJSON when fext is JSON



    config file  json or hjon

    {
      "dt": "2021-01-01T00:00:00.000000+00:00",
      "nel":
      {
        "dt": "2021-01-01T00:00:00.000000+00:00",
        "curls":
        [
          "tcp://localhost:5621/"
        ]
      },
      "iurls":
      [
        "tcp://localhost:5620/?role=peer&name=tam"
      ],
      "durls":
      [
        "http://127.0.0.1:7723/oobi/EBNaNu-M9P5cgrnfl2Fvymy4E_jvxxyjb70PRtiANlJy",
        "http://127.0.0.1:7723/oobi/EMhvwOlyEJ9kN4PrwCpr9Jsv7TxPhiYveZ0oP3lJzdEi",
      ],
      "wurls":
      [
        "http://127.0.0.1:5644/.well-known/keri/oobi/EBNaNu-M9P5cgrnfl2Fvymy4E_jvxxyjb70PRtiANlJy?name=Root"
      ]
    }
    """
    TailDirPath = os.path.join("keri", "cf")
    CleanTailDirPath = os.path.join("keri", "clean", "cf")
    AltTailDirPath = os.path.join(".keri", "cf")
    AltCleanTailDirPath = os.path.join(".keri", "clean", "cf")
    TempPrefix = "keri_cf_"

    def __init__(self, name="conf", base="main", filed=True, mode="r+b",
                 fext="json", human=True, **kwa):
        """
        Setup config file .file at .path

        Parameters:
            name (str): directory path name differentiator directory/file
                When system employs more than one keri installation, name allows
                differentiating each instance by name
            base (str): optional directory path segment inserted before name
                that allows further differentiation with a hierarchy. "" means
                optional.
            temp (bool): assign to .temp
                True then open in temporary directory, clear on close
                Otherwise then open persistent directory, do not clear on close
            headDirPath (str): optional head directory pathname for main database
                Default .HeadDirPath
            perm (int): optional numeric os dir permissions for database
                directory and database files. Default .DirMode
            reopen (bool): True means (re)opened by this init
                           False  means not (re)opened by this init but later
            clear (bool): True means remove directory upon close if reopon
                          False means do not remove directory upon close if reopen
            reuse (bool): True means reuse self.path if already exists
                          False means do not reuse but remake self.path
            clean (bool): True means path uses clean tail variant
                             False means path uses normal tail variant
            filed (bool): True means .path is file path not directory path
                          False means .path is directory path not file path
            mode (str): File open mode when filed default non-truncate r+w
            fext (str): File extension when filed
            human(bool): True means use human friendly HJSON when fext is json

        """
        super(FileConfiger, self).__init__(name=name,
                                           base=base,
                                           filed=filed,
                                           mode=mode,
                                           fext=fext,
                                           **kwa)
        self.human = True if human else False


    def put(self, data: dict, human=None):
        """
        Serialize data dict and write to file given by .path where serialization is
        given by .fext path's extension of either JSON, MsgPack, or CBOR for extension
        .json, .mgpk, or .cbor respectively

        Parameters:
            data (dict): to be serialized per file extension on .path

        Raises:
            IOError if unsupported file extension
        """
        if not self.file or self.file.closed:
            raise ValueError(f"File '{self.path}' not opened.")

        human = human if human is not None else self.human
        self.file.seek(0)
        self.file.truncate()
        root, ext = os.path.splitext(self.path)
        if ext == '.json':  # json can't dump to binary
            if human:
                ser = hjson.dumps(data)
            else:
                ser = json.dumps(data, indent=2)
            ser = ser.encode("utf-8")
        elif ext == '.mgpk':
            ser = msgpack.dumps(data)
        elif ext == '.cbor':
            ser = cbor.dumps(data)
        else:
            raise IOError(f"Invalid file path ext '{ext}' "
                          f"not '.json', '.mgpk', or 'cbor'.")
        self.file.write(ser)
        self.file.flush()
        os.fsync(self.file.fileno())
        return True


    def get(self, human=None):
        """
        Returns:
            data (dict): converted from contents of file path given extention
                         empty dict if empty file

        Raises:
            IOError if unsupported file extension

        file may be either json, msgpack, or cbor given by extension .json, .mgpk, or
        .cbor respectively

        """
        if not self.file or self.file.closed:
            raise ValueError(f"File '{self.path}' not opened.")

        human = human if human is not None else self.human
        it = {}
        self.file.seek(0)
        ser = self.file.read()
        if ser:  # not empty
            root, ext = os.path.splitext(self.path)
            if ext == '.json':  # json.load works with bytes as well as str
                if human:
                    it = hjson.loads(ser.decode("utf-8"))
                else:
                    it = json.loads(ser.decode("utf-8"))
            elif ext == '.mgpk':
                it = msgpack.loads(ser)
            elif ext == '.cbor':
                it = cbor.loads(ser)
            else:
                raise IOError(f"Invalid file path ext '{ext}' "
                             f"not '.json', '.mgpk', or 'cbor'.")
        return it


Configer = FileConfiger  # backward compatibility - keria and CLI reference this name


class DictConfiger(Sourcer):
    """In-memory config backed by a dict. No filesystem required.

    Concrete Sourcer implementation for use with Habery/Hab in
    environments without a writable filesystem (e.g., AWS Lambda,
    serverless, in-memory testing).
    """

    def __init__(self, data=None, *, name="conf", base="main", temp=False, **kwa):
        """
        Parameters:
            data (dict|None): initial config data.  None means empty dict.
            name (str): identifier name (mirrors Configer)
            base (str): base path segment (mirrors Configer)
            temp (bool): temporary flag (mirrors Configer)
        """
        self.name = name
        self.base = base
        self.temp = temp
        self._data = data if data is not None else {}
        self.opened = True
        self.path = None

    def get(self):
        """Return copy of config data dict."""
        return dict(self._data)

    def put(self, data):
        """Replace config data.

        Parameters:
            data (dict): new config data

        Returns:
            bool: True on success
        """
        self._data = dict(data)
        return True

    def close(self, clear=False):
        """Mark as closed.

        Parameters:
            clear (bool): ignored, present for Configer API compatibility
        """
        self.opened = False

    def reopen(self, **kwa):
        """Mark as opened.

        Returns:
            bool: True on success
        """
        self.opened = True
        return True


class ConfigerDoer(doing.Doer):
    """
    Basic Filer Doer

    Attributes:
        done (bool): completion state:
            True means completed
            Otherwise incomplete. Incompletion maybe due to close or abort.
        configer (Configer): instance

    Properties:
        tyme (float): relative cycle time of associated Tymist .tyme obtained
            via injected .tymth function wrapper closure.
        tymth (func): closure returned by Tymist .tymeth() method.
            When .tymth is called it returns associated Tymist .tyme.
            .tymth provides injected dependency on Tymist tyme base.
        tock (float)): desired time in seconds between runs or until next run,
                 non negative, zero means run asap

    """

    def __init__(self, configer, **kwa):
        """
        Parameters:
           tymist (Tymist): instance
           tock (float): initial value of .tock in seconds
           configer (Configer): instance
        """
        super(ConfigerDoer, self).__init__(**kwa)
        self.configer = configer

    def enter(self, *, temp=None):
        """"""
        if not self.configer.opened:
            self.configer.reopen()  # reopen(temp=temp)

    def exit(self):
        """"""
        self.configer.close(clear=self.configer.temp)
