"""ServiceAidFrameworkLayer: prebuilt arm64 Lambda layer carrying the
keri_serviceaid framework package (handler entry, pipeline, contract, default
providers). Pairs with KeriRuntimeLayer (libsodium + keripy native deps) so a
Service-AID Function deploys as a pure-Python zip: the dev's compute_code asset +
two layers.

Layer layout (Lambda extracts a layer zip to /opt):
  python/ -> /opt/python   (on sys.path: keri_serviceaid)

Build the asset with keri_cdk/layers/build_framework_layer.sh. The asset dir
keri_cdk/layers/serviceaid_framework/ is gitignored and regenerated by the build."""
import os

from aws_cdk import aws_lambda as _lambda
from constructs import Construct

_ASSET = os.path.join(os.path.dirname(__file__), "layers", "serviceaid_framework")


class ServiceAidFrameworkLayer(Construct):
    """Prebuilt arm64 layer carrying the keri_serviceaid framework package.
    Build with keri_cdk/layers/build_framework_layer.sh."""

    def __init__(self, scope, cid, *, asset_path=_ASSET, **kw):
        super().__init__(scope, cid, **kw)
        self.layer = _lambda.LayerVersion(
            self, "ServiceAidFramework",
            code=_lambda.Code.from_asset(asset_path),
            compatible_runtimes=[_lambda.Runtime.PYTHON_3_14],
            compatible_architectures=[_lambda.Architecture.ARM_64],
            description="keri_serviceaid framework package (arm64)")
