"""KeriRuntimeLayer: prebuilt arm64 Lambda layer carrying libsodium + keripy's
native deps, so consumer stacks deploy pure-Python *zip* functions with NO Docker
at deploy time.

Layer layout (Lambda extracts a layer zip to ``/opt``):
  python/   -> /opt/python   (on sys.path: keri + all pip deps)
  lib/      -> /opt/lib       (native .so; reachable via LD_LIBRARY_PATH=/opt/lib)

Build the asset with ``keri_cdk/layers/build_layer.sh`` (runs inside the AL
arm64 image so wheels and the libsodium .so match the Lambda runtime). The asset
dir ``keri_cdk/layers/keri_runtime/`` is gitignored and regenerated by the build.
"""
import glob
import hashlib
import os

from aws_cdk import aws_lambda as _lambda
from constructs import Construct

_ASSET = os.path.join(os.path.dirname(__file__), "layers", "keri_runtime")
_SRC_KERI = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", "src", "keri"))


def _keri_tree_hash(root):
    """Content hash of every ``*.py`` under ``root`` keyed by path relative to
    ``root`` (so src/keri and the layer's python/keri compare apples-to-apples).
    Returns None if ``root`` is absent."""
    if not os.path.isdir(root):
        return None
    h = hashlib.sha256()
    for path in sorted(glob.glob(os.path.join(root, "**", "*.py"), recursive=True)):
        if "__pycache__" in path:
            continue
        h.update(os.path.relpath(path, root).encode())
        with open(path, "rb") as fh:
            h.update(fh.read())
    return h.hexdigest()


def assert_layer_fresh(asset_path=_ASSET, src_keri=_SRC_KERI):
    """Fail synth/deploy if the built layer's ``keri`` diverges from the source
    ``keri`` — i.e. someone edited keri but did not rebuild the layer, so a
    deploy would silently ship stale runtime code (the exact trap that cost a
    long debugging detour). Set KERI_SKIP_LAYER_FRESH_CHECK=1 to bypass.
    """
    if os.environ.get("KERI_SKIP_LAYER_FRESH_CHECK") == "1":
        return
    layer_keri = os.path.join(asset_path, "python", "keri")
    src_hash = _keri_tree_hash(src_keri)
    layer_hash = _keri_tree_hash(layer_keri)
    if src_hash is None:
        return  # source tree not co-located (e.g. installed keri); nothing to compare
    if layer_hash is None:
        raise RuntimeError(
            f"KeriRuntimeLayer asset missing keri at {layer_keri}. "
            f"Build it first: bash keri_cdk/layers/build_layer.sh")
    if src_hash != layer_hash:
        raise RuntimeError(
            "KeriRuntimeLayer is STALE: src/keri has changed since the layer was "
            "built, so deploying now would ship out-of-date runtime code. "
            "Rebuild the layer FIRST:\n"
            "    bash keri_cdk/layers/build_layer.sh\n"
            "(or set KERI_SKIP_LAYER_FRESH_CHECK=1 to bypass intentionally).")


class KeriRuntimeLayer(Construct):
    """Prebuilt arm64 layer: libsodium + keripy native deps, so consumers deploy
    pure-Python zip functions with no Docker. Build with
    keri_cdk/layers/build_layer.sh."""

    def __init__(self, scope, cid, *, asset_path=_ASSET, **kw):
        super().__init__(scope, cid, **kw)
        assert_layer_fresh(asset_path)
        # keripy's setup.py pins python_requires='>=3.14.0', so the layer must
        # target the python3.14 managed runtime (GA in Lambda since Nov 2025).
        # python3.13 cannot even pip-install keri.
        self.layer = _lambda.LayerVersion(
            self, "KeriRuntime",
            code=_lambda.Code.from_asset(asset_path),
            compatible_runtimes=[_lambda.Runtime.PYTHON_3_14],
            compatible_architectures=[_lambda.Architecture.ARM_64],
            description="libsodium + keripy native deps (arm64)")
