"""KeriRuntimeLayer: prebuilt arm64 Lambda layer carrying libsodium + keripy's
native deps, so consumer stacks deploy pure-Python *zip* functions with NO Docker
at deploy time.

Layer layout (Lambda extracts a layer zip to ``/opt``):
  python/   -> /opt/python   (on sys.path: keri + all pip deps)
  lib/      -> /opt/lib       (native .so; reachable via LD_LIBRARY_PATH=/opt/lib)

Build the asset with ``keri_cdk/layers/build_layer.sh`` (runs inside the AL
arm64 image so wheels and the libsodium .so match the Lambda runtime). The asset
dir ``keri_cdk/layers/keri_runtime/`` is gitignored and regenerated by the build.
"""
import os

from aws_cdk import aws_lambda as _lambda
from constructs import Construct

_ASSET = os.path.join(os.path.dirname(__file__), "layers", "keri_runtime")


class KeriRuntimeLayer(Construct):
    """Prebuilt arm64 layer: libsodium + keripy native deps, so consumers deploy
    pure-Python zip functions with no Docker. Build with
    keri_cdk/layers/build_layer.sh."""

    def __init__(self, scope, cid, *, asset_path=_ASSET, **kw):
        super().__init__(scope, cid, **kw)
        # keripy's setup.py pins python_requires='>=3.14.0', so the layer must
        # target the python3.14 managed runtime (GA in Lambda since Nov 2025).
        # python3.13 cannot even pip-install keri.
        self.layer = _lambda.LayerVersion(
            self, "KeriRuntime",
            code=_lambda.Code.from_asset(asset_path),
            compatible_runtimes=[_lambda.Runtime.PYTHON_3_14],
            compatible_architectures=[_lambda.Architecture.ARM_64],
            description="libsodium + keripy native deps (arm64)")
